### ISSUE TITLE
Provide RPM/Deb repositories

### ISSUE THREAD

**Issue by TommyTran732** [ente-io/photos-desktop#104]
Right now, RPM and DEB packages need to be updated manually. AppImages is not ideal, as one would need to run the app to have it update itself (which is inconvenient on system like Qubes as the AppVM would be off most of the time) and does not integrate well with various desktop environments.

It will be much better if ente provides RPM/Deb repositories. You could use COPR (https://copr.fedorainfracloud.org/) or OBS (https://build.opensuse.org/) if you don't want to host the repository yourself.

**Comment by mnvr** [comment]
@tommytran732 Thank you for the links to COPR and OBS! Let us take a look...

**Comment by mnvr** [comment]
Closing this for now, given the proliferation of distribution channels we'd like to first focus on adding as many binary formats as we can but stick to distributing them via GitHub releases. But this can be revisited in the future.
