### ISSUE TITLE
Too much memory use on upload

### ISSUE THREAD

**Issue by rcsilva83** [ente-io/photos-desktop#116]
I just bought the a 500GB subscription and I'm trying to make an upload of my entire "Photos" folder but the application uses too much memory and the application is closed by SO. I tried both "Upload" and "Watch folder" option and I have problems with both.

SO: Fedora 37
RAM: 4GB
App version: 1.6.14 (AppImage)
Folder total size: 95,6 GB (10.755 files on 119 folders)
Album option: multiple albums

Interestingly, I could upload a bigger folder before (174,1 GB; 27.306 files) but it doesn't have so many folders and I uploaded all of them to the same album.

**Comment by abhinavkgrd** [comment]
Hii, @rcsilva83, Thank you for reporting this... I will try to reproduce the crash with your conditions and try to fix the issue.

If we figure out something and can make some improvements, we will make a beta release which you test out to confirm if the fix worked for you.

Cheers

**Comment by rcsilva83** [comment]
Hi, I deleted application cache (`.cache/ente` and `.config/ente`) and then I tried to upload just one sub-folder and I had the same problem. Perhaps this is related with my account having 190GB used (just guessing)...

**Comment by abhinavkgrd** [comment]
Hey @rcsilva83, we have tried to fix some of the issues you reported here: [v1.6.15-beta.3](https://github.com/ente-io/bhari-frame/releases/tag/v1.6.15-beta.3).

Could you please try uploading data (directly, without Watch Folders), and let us know how it goes?

Thanks a lot!

**Comment by rcsilva83** [comment]
It didn't work...

**Comment by mnvr** [comment]
Possibly outdated. If it is still occurring please reopen!
