### ISSUE TITLE
Uploading google takeout via AppImage gets stuck

### ISSUE THREAD

**Issue by SpyrosRoum** [ente-io/photos-desktop#117]
Hello, I'm trying to upload my Google Takeout (a 22GB ZIP file) using the AppImage version of the app but it gets stuck on the 512th file, which is a 30 seconds 1080p mp4 video.

I tried restarting it a few times and it always reaches that point and then does seemingly nothing, the cpu usage goes down as well.

It's probably not related but might be worth noting that as soon as I open the app I get this message on the terminal:
```
[48304:1212/181923.190985:ERROR:browser_main_loop.cc(269)] Gdk: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed
Error occurred in handler for 'safeStorage-encrypt': Error: Error while decrypting the ciphertext provided to safeStorage.decryptString. Encryption is not available.
    at /tmp/.mount_ente-11h8ucu/resources/app.asar/app/utils/ipcComms.js:73:39
    at node:electron/js2c/browser_init:193:567
    at EventEmitter.<anonymous> (node:electron/js2c/browser_init:165:11606)
    at EventEmitter.emit (node:events:527:28)
    at EventEmitter.emit (node:domain:475:12)
    at emitter.emit (/tmp/.mount_ente-11h8ucu/resources/app.asar/node_modules/@sentry/electron/dist/main/integrations/electron.js:63:25)
```
However files still upload fine (up to no. 512)

Any idea what this might be about?

**Comment by vishnukvmd** [comment]
Hey! Sorry about this! Could you please try uploading only this specific MP4 file (without the rest) and let us know the outcome?

Thank you!

**Comment by SpyrosRoum** [comment]
Trying to upload the single file only gives me an error saying that 'ente does not support these file formats yet`.

So I have two questions/notes about this:
1. How could this be the case, since I have successfully uploaded other videos and there should be nothing special about this one either
2. If this is why the upload hanged earlier, I would consider that a bug, there should be a way to skip it and just let me know that the upload for this file failed or something like that

**Comment by vishnukvmd** [comment]
You're absolutely right on both fronts! This is how we normally treat invalid files, we aren't sure why the behavior is breaking here.

Could you please click on Help > View logs and email those files to support@ente.io? We'd like to dig into the root cause.

Thanks in advance! 🙏

**Comment by abhinavkgrd** [comment]
Hey @SpyrosRoum, we have added some checks to fix this issue here: [v1.6.15-beta.3](https://github.com/ente-io/bhari-frame/releases/tag/v1.6.15-beta.3)

Could you please check this at your convenience and let us know if things are working fine?

Thanks a bunch!

**Comment by SpyrosRoum** [comment]
Hello again!
First of all, I really like the new beta, It spent most of last night doing its job. Out of the total ~8000 files it had to upload, there are ~2000 left.

Unfortunately though, today it seems like progress has slowed down a lot, maybe even stopped again. It seems to be stuck with 0% progress on 4 mp4s that are from around the same period as the one causing issues last time.

I have stumbled onto another issue as well, which was present before but it would solve itself after re-starting the app a couple of times. (Let me know if you'd like me to open a new issue for this)

When clicking on the `X` to cancel the upload, after confirming, I get another pop-up that says `Cancelling remaining uploads` and that never ends. If I restart the app it automatically tries to resume uploading the stuck files, clicking `X` again causes the same broken behavior.

**Comment by abhinavkgrd** [comment]
Hello again @SpyrosRoum, We were able to find the root cause of the issue 😄, and made a release fixing it too.
You can check it out at [v1.6.16](https://github.com/ente-io/photos-desktop/releases/tag/v1.6.16). 

Thank you for your patience !!

Please let us know if you are still facing any issues. 

Cheers!!

**Comment by SpyrosRoum** [comment]
I was finally able to upload everything,

So far I really like this app and how it truly just does its job on the background of my phone, 
I also love how responsive you are

Thank you!
