### ISSUE TITLE
Save As/Download Location

### ISSUE THREAD

**Issue by SpoofingMyName** [ente-io/photos-desktop#194]
Currently when clicking the download button it saves images/videos directly to your downloads folder. It would be nice if there was an option to choose where it saves to.

**Comment by vishnukvmd** [comment]
Design: https://www.figma.com/file/SYtMyLBs5SAOkTbfMMzhqt/ente-Visual-Design?type=design&node-id=8437-49844&mode=design&t=t3LWPXc3KrwkqaBw-4

**Comment by abhinavkgrd** [comment]
Released in [v1.6.41](https://github.com/ente-io/photos-desktop/releases/tag/v1.6.41) ✨
