### ISSUE TITLE
Incremental Backup/Export

### ISSUE THREAD

**Issue by gigibytes** [ente-io/photos-desktop#207]
Would be nice to have ente remember the last time you exported data was, and offer an option to only export/backup what is new since then.

I'm not sure if the 'sync continuously' option does this (or what it does if you disconnect the drive, which is what i plan to do)?

**Comment by vishnukvmd** [comment]
Hey! Export by default is incremental in nature. You can pause at any point, and whenever you resume (provided you're exporting data to the same root folder), we will resume instead of starting afresh.
