### ISSUE TITLE
Unable to return previously hidden photos to the source album(s) automatically.

### ISSUE THREAD

**Issue by jonathantullett** [ente-io/photos-desktop#233]
When using the 'hide' functionality to prevent photos from displaying in general album galeries, it's not possible to 'unhide' the picture and automatically it return to the album it was previously in - you're asked where you want it to go.

I would expect unhiding a picture to re-add it (or unmask it) in the albums it was originally in, without having to remember where it was.

Having inadvertently hidden a bunch of photos through bad mis-multiselect, I'm in a position where I can't easily get things back where they were.

Is there anything I can do with the existing tooling?

**Comment by vishnukvmd** [comment]
Hey @jonathantullett, sorry, when you hide files we currently remove **all links** it had with its previous album, so unfortunately there is no easy way to move them back in to their original album :(

I'm hoping that you'll be able to multi-select and move them back in one go 🤞

**Comment by jonathantullett** [comment]
> I'm hoping that you'll be able to multi-select and move them back in one go

Sadly not, it was across a number of albums. Losing that association makes me uneasy using the functionality in general. Are there techincal reasons the linkage can't be maintained so it's able to be restored later on?

**Comment by vishnukvmd** [comment]
So `hidden` is not designed to be just an attribute on a file. We move it to a separate `collection` (album) with a different `decryptionKey` associated with it. This was done to make sure that you can freely share an album without worrying about the access-control of the hidden items within it.

**Comment by jonathantullett** [comment]
Ah, I see the limitation then.

It would be ideal if when hiding the photo, the metadata was updated to save where it was hidden from and that being reversible though unhiding it.

Aggregating a bunch of disparate pictures into a single album and not bring able to view them back in their original homes/albums makes the tool unusable for my case, sadly.
