### ISSUE TITLE
Open photos from continuous backup

### ISSUE THREAD

**Issue by semberal** [ente-io/photos-desktop#253]
Hi,

first of all, thanks for ente, it is a fantastic product and I enjoy using it a lot!

I am using ente desktop on Mac with continuous syncing, so my entire library is essentially always fully backed up on disk. When I open a photo in ente-desktop, there is a short delay while the full resolution photo is being downloaded and decrypted. The experience gets worse when I am just skimming through many photos because these delays add up. Would it be possible to fetch the photo from the backup, if it exists, instead of downloading it from ente servers?

**Comment by vishnukvmd** [comment]
Hey @semberal, we're tracking this @ https://github.com/ente-io/photos-desktop/issues/231. It'd be great if you could give a 👍.

I'll close this issue in favor of that. Please reopen if you think I missed something!
