### ISSUE TITLE
Pin, Hello ETC to enable staying logged in with Ente secure from unauthorized viewing on desktop.

### ISSUE THREAD

**Issue by Mr-Hitchens** [ente-io/photos-desktop#256]
There is no way to leave ENTE uploading or anything else securely on desktop. I can only log out to stop snooping. During uploading or just using ENTE there is nothing to stop anyone with desktop access from looking around unhindered. No, I don't want to hide every folder, that's silly. This seems like a huge oversight. I can name several of your competitors that have this function. Have I missed something? It's a very strange omission from a security-based application.

**Comment by vishnukvmd** [comment]
Closing in favor of https://github.com/ente-io/photos-web/issues/1426.
