### ISSUE TITLE
Support for audio files

### ISSUE THREAD

**Issue by hadrienj** [ente-io/photos-desktop#258]
I have a lot of audio recordings that I use similarly as photos and it would be great to be able to store them the same way as photos and videos. For instance, I use formats like `mp3`, `wav`, `flac`, etc.

**Comment by vishnukvmd** [comment]
Hey, thanks for raising this request! We're thinking about building a separate app to handle generic files. We'd like to keep the Photos app separate from it, to reduce complexity in both implementation and end-user experience. So I'll close this issue for now, but please stay tuned 🙂
