### ISSUE TITLE
Linux aarch64 binaries

### ISSUE THREAD

**Issue by jayna37** [ente-io/photos-desktop#282]
Issue: Only x86 binaries are provided, but my machines are all aarch64 based.

Suggestion: Provide packages for Linux aarch64 (AppImage, rpm, deb etc.)

**Comment by abhinavkgrd** [comment]
Heyy @jayna37, I have created a [beta release](https://github.com/ente-io/photos-desktop/releases/tag/v1.6.59-beta.0), which has aarch64 Linux binaries. 

Can you please test it out and let us know if its working as expected

**Comment by jayna37** [comment]
Hello @abhinavkgrd thanks a lot. I have been testing it a bit and it works fine, I have not found any bugs. If anything comes up later down the line I will of course raise it here but it seems to be all in working order.
