### ISSUE TITLE
Albums - add/move photo loads destination album when complete - Desktop

### ISSUE THREAD

**Issue by s38b35M5** [ente-io/photos-desktop#297]
When moving or adding one or more photos to an album, ente desktop will process the request, and when complete, will load the destination. This can make library maintenance tedious as you have to keep finding the album or photo location you were in to return to work.

Would prefer if the application did not change the current album after this move/add operation.

`Version: 1.6.59`
`Platform: Linux x64`

**Comment by abhinavkgrd** [comment]
closing in favor of https://github.com/ente-io/photos-web/issues/1554
