### ISSUE TITLE
Bulk Editing of 'Taken Time' and 'Date' in EXIF Data

### ISSUE THREAD

**Issue by samirugamage** [ente-io/photos-desktop#299]
I would greatly appreciate the addition of a bulk editing feature in Ente Photos software, specifically for modifying the 'taken time' and 'date' in EXIF data, to enhance user experience.

**Comment by vishnukvmd** [comment]
Hey, this is already possible.

You can multi-select files, and click on the "Fix time" option on the action bar that pops up.

Please reopen the issue if you were looking for something else!
