### ISSUE TITLE
Add a free-form crop

### ISSUE THREAD

**Issue by quietmansoath** [ente-io/photos-desktop#300]
Being able to adjust a photo's aspect ratio is nice, but is far too limiting. I often need to crop photos I take and there's no way to do this if I only, for example, want to remove the left edge of a photo.

Please create a free-form crop tool. The one that works in Google Photos, or even Windows' photo viewer, is a good example.

**Comment by mnvr** [comment]
I think this was completed as part of https://github.com/ente-io/photos-web/pull/1538. Closing.
