### ISSUE TITLE
Fix thumbnails with incorrect orientations

### ISSUE THREAD

**Issue by vishnukvmd** [ente-io/photos-desktop#306]
Thumbnails for photos that had orientation information within the EXIF (eg. those that were rotated after being captured), were generated incorrectly. We've [fixed this issue](https://github.com/ente-io/photos-desktop/commit/500ae282aa714d575d65603ff12b16d39a34bff7) in `v1.6.60`.

However, existing files whose thumbnails were incorrectly rotated are yet to be patched.

The fix could be the client pulling all thumbnails, comparing the aspect ratio with that of the original image, and when a disparity is encountered, updating the thumbnail for that specific photo.

**Comment by vishnukvmd** [comment]
Hey @ElijahHW, we discussed this internally. If 90%+ items are affected, the best bet would be to export and re-import.

Any fix we apply would unfortunately require us to pull the original photos to regenerate the thumbnails, and we are yet to understand the impact of the issue to assign a priority to it.

In the meantime, if you perform a full export, clear your library and re-import using the latest version of the Desktop app, everything should fall back into place.

I understand this is a non-trivial workaround, and if you could reach out to support@ente.io, we'd love to figure out a way to make it up to you.

**Comment by ElijahHW** [comment]
Okay I will attempt that then, although it might take a while as I have a lot of GBs backed up. I'll come back to you when its done.

**Comment by mnvr** [comment]
Instead of moving this to the new repo (https://github.com/ente-io/ente), I'll tentatively close this. Please reopen if this wasn't satisfactorily solved!
