### ISSUE TITLE
All photo edits to save over the original without changing metadata

### ISSUE THREAD

**Issue by quietmansoath** [ente-io/photos-desktop#317]
If I make an edit to the photo, say the brightness, I have to manually "save a copy to ente" which then defaults the image to today.

I want the options to 1. default to overwriting the image I was editing and 2. overwrite that image with the metadata of the original image.

**Comment by vishnukvmd** [comment]
Hey, just fyi - we had initially tried this, but updating EXIF is tricky for certain image formats (like HEIC).

Will keep this issue open.

**Comment by mnvr** [comment]
Closing in favor of https://github.com/ente-io/ente/issues/576 (just consolidating duplicates, both are the same)
