### ISSUE TITLE
Add to Homebrew

### ISSUE THREAD

**Issue by MarcMogdanz** [ente-io/photos-desktop#7]
It would be nice if you could the desktop app of ente to Homebrew.

**Comment by vishnukvmd** [comment]
@Abhinav-grd please look at this once your Macbook is delivered. :)

**Comment by mrghostface** [comment]
Hi there! Bumping this issue as I would also really like for ente to be added as a cask to Homebrew.

**Comment by abhinavkgrd** [comment]
Hi @mrghostface, ente is now available on Homebrew https://formulae.brew.sh/cask/ente 😄
